# Generated by Django 2.0 on 2020-04-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
