# Generated by Django 2.0 on 2020-04-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0004_auto_20200416_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
